name: Continuous Integration
run-name: ${{ github.actor }} has triggered continuous integration workflow

on:
    push:
    pull_request:

jobs:
    continuous-integration:
        name: Continuous Integration
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22"
                  cache: "npm"

            - name: Clean install
              run: npm ci

            - name: Run ESLint
              run: npm run lint

            - name: Build
              run: npm run build
